In [1]:
import pandas as pd

In [14]:
df = pd.read_csv("boulderweather.csv")

In [15]:
df

,DATE,HourlyDewPointTemperature,HourlyDryBulbTemperature,HourlyPrecipitation,HourlyPresentWeatherType,HourlyRelativeHumidity,HourlySkyConditions,HourlyStationPressure,HourlyVisibility,HourlyWetBulbTemperature,HourlyWindDirection,HourlyWindGustSpeed,HourlyWindSpeed,Sunrise,Sunset
0,2022-01-01T00:15:00,10.0,12.0,NaN,NaN,92.0,BKN:07 9 OVC:08 13,24.43,NaN,11.0,050,NaN,8.0,NaN,NaN
1,2022-01-01T00:35:00,10.0,12.0,NaN,NaN,92.0,OVC:08 9,24.44,NaN,11.0,050,NaN,5.0,NaN,NaN
2,2022-01-01T00:55:00,9.0,12.0,NaN,NaN,85.0,OVC:08 9,24.44,NaN,11.0,030,NaN,5.0,NaN,NaN
3,2022-01-01T01:15:00,9.0,10.0,NaN,NaN,92.0,OVC:08 9,24.44,NaN,10.0,020,NaN,5.0,NaN,NaN
4,2022-01-01T01:35:00,9.0,10.0,NaN,NaN,92.0,OVC:08 9,24.44,NaN,10.0,040,NaN,5.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12604,2022-06-22T23:55:00,41.0,63.0,NaN,NaN,45.0,CLR:00,24.79,10.0,51.0,000,NaN,0.0,NaN,NaN
12605,2022-06-22T23:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,432.0,1933.0
12606,2022-06-23T00:15:00,41.0,63.0,NaN,NaN,45.0,CLR:00,24.79,10.0,51.0,180,NaN,3.0,NaN,NaN
12607,2022-06-23T00:35:00,36.0,64.0,NaN,NaN,34.0,CLR:00,24.78,10.0,49.0,200,NaN,5.0,NaN,NaN
12608,2022-06-23T00:55:00,37.0,64.0,NaN,NaN,37.0,CLR:00,24.78,10.0,50.0,000,NaN,0.0,NaN,NaN

In [16]:
df.shape

(12609, 15)

In [17]:
df.info

<bound method DataFrame.info of                       DATE  HourlyDewPointTemperature  \
0      2022-01-01T00:15:00                       10.0
1      2022-01-01T00:35:00                       10.0
2      2022-01-01T00:55:00                        9.0
3      2022-01-01T01:15:00                        9.0
4      2022-01-01T01:35:00                        9.0
...                    ...                        ...
12604  2022-06-22T23:55:00                       41.0
12605  2022-06-22T23:59:00                        NaN
12606  2022-06-23T00:15:00                       41.0
12607  2022-06-23T00:35:00                       36.0
12608  2022-06-23T00:55:00                       37.0

       HourlyDryBulbTemperature  HourlyPrecipitation HourlyPresentWeatherType  \
0                          12.0                  NaN                      NaN
1                          12.0                  NaN                      NaN
2                          12.0                  NaN                      NaN
3                          10.0                  NaN                      NaN
4                          10.0                  NaN                      NaN
...                         ...                  ...                      ...
12604                      63.0                  NaN                      NaN
12605                       NaN                  NaN                      NaN
12606                      63.0                  NaN                      NaN
12607                      64.0                  NaN                      NaN
12608                      64.0                  NaN                      NaN

       HourlyRelativeHumidity HourlySkyConditions  HourlyStationPressure  \
0                        92.0  BKN:07 9 OVC:08 13                  24.43
1                        92.0            OVC:08 9                  24.44
2                        85.0            OVC:08 9                  24.44
3                        92.0            OVC:08 9                  24.44
4                        92.0            OVC:08 9                  24.44
...                       ...                 ...                    ...
12604                    45.0              CLR:00                  24.79
12605                     NaN                 NaN                    NaN
12606                    45.0              CLR:00                  24.79
12607                    34.0              CLR:00                  24.78
12608                    37.0              CLR:00                  24.78

       HourlyVisibility  HourlyWetBulbTemperature HourlyWindDirection  \
0                   NaN                      11.0                 050
1                   NaN                      11.0                 050
2                   NaN                      11.0                 030
3                   NaN                      10.0                 020
4                   NaN                      10.0                 040
...                 ...                       ...                 ...
12604              10.0                      51.0                 000
12605               NaN                       NaN                 NaN
12606              10.0                      51.0                 180
12607              10.0                      49.0                 200
12608              10.0                      50.0                 000

      HourlyWindGustSpeed  HourlyWindSpeed  Sunrise  Sunset
0                     NaN              8.0      NaN     NaN
1                     NaN              5.0      NaN     NaN
2                     NaN              5.0      NaN     NaN
3                     NaN              5.0      NaN     NaN
4                     NaN              5.0      NaN     NaN
...                   ...              ...      ...     ...
12604                 NaN              0.0      NaN     NaN
12605                 NaN              NaN    432.0  1933.0
12606                 NaN              3.0      NaN     NaN
12607                 NaN              5.0      NaN     NaN
12608                 NaN              0.0      NaN     NaN

[12609 rows x 15 columns]>

In [19]:
df.columns

Index(['DATE', 'HourlyDewPointTemperature', 'HourlyDryBulbTemperature',
       'HourlyPrecipitation', 'HourlyPresentWeatherType',
       'HourlyRelativeHumidity', 'HourlySkyConditions',
       'HourlyStationPressure', 'HourlyVisibility', 'HourlyWetBulbTemperature',
       'HourlyWindDirection', 'HourlyWindGustSpeed', 'HourlyWindSpeed',
       'Sunrise', 'Sunset'],
      dtype='object')

In [20]:
df.head()

,DATE,HourlyDewPointTemperature,HourlyDryBulbTemperature,HourlyPrecipitation,HourlyPresentWeatherType,HourlyRelativeHumidity,HourlySkyConditions,HourlyStationPressure,HourlyVisibility,HourlyWetBulbTemperature,HourlyWindDirection,HourlyWindGustSpeed,HourlyWindSpeed,Sunrise,Sunset
0,2022-01-01T00:15:00,10.0,12.0,NaN,NaN,92.0,BKN:07 9 OVC:08 13,24.43,NaN,11.0,050,NaN,8.0,NaN,NaN
1,2022-01-01T00:35:00,10.0,12.0,NaN,NaN,92.0,OVC:08 9,24.44,NaN,11.0,050,NaN,5.0,NaN,NaN
2,2022-01-01T00:55:00,9.0,12.0,NaN,NaN,85.0,OVC:08 9,24.44,NaN,11.0,030,NaN,5.0,NaN,NaN
3,2022-01-01T01:15:00,9.0,10.0,NaN,NaN,92.0,OVC:08 9,24.44,NaN,10.0,020,NaN,5.0,NaN,NaN
4,2022-01-01T01:35:00,9.0,10.0,NaN,NaN,92.0,OVC:08 9,24.44,NaN,10.0,040,NaN,5.0,NaN,NaN

In [ ]:
df.tail(10)